specVersion: 1.0.0
name: stargaze-subql-starter
version: 0.0.1
runner:
  node:
    name: '@subql/node-cosmos'
    version: '>=0.1.0'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  This project can be use as a starting point for developing your Cosmos
  (Stargaze) based SubQuery project
repository: 'https://github.com/subquery/cosmos-subql-starter'
schema:
  file: ./schema.graphql
network:
  chainId: stargaze-1
  endpoint: 'http://nodes.stargaze-1.publicawesome.dev:26657/'
  dictionary: 'https://api.subquery.network/sq/subquery/cosmos-stargaze-dictionary'
  chainTypes:
    cosmos.slashing.v1beta1:
      file: ./proto/cosmos/slashing/v1beta1/tx.proto
      messages:
        - MsgUnjail
    cosmos.gov.v1beta1:
      file: ./proto/cosmos/gov/v1beta1/tx.proto
      messages:
        - MsgVoteWeighted
    cosmos.gov.v1beta1.gov:
      file: ./proto/cosmos/gov/v1beta1/gov.proto
      messages:
        - WeightedVoteOption
    publicawesome.stargaze.claim.v1beta1:
      file: ./proto/stargaze/claim/v1beta1/tx.proto
      messages:
        - MsgInitialClaim
dataSources:
  - kind: cosmos/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: cosmos/EventHandler
          filter:
            type: execute
            messageFilter:
              type: /cosmwasm.wasm.v1.MsgExecuteContract
        - handler: handleMessage
          kind: cosmos/MessageHandler
          filter:
            type: /cosmwasm.wasm.v1.MsgExecuteContract
