name: PR
on:
  pull_request:
    paths-ignore:
      - ".github/workflows/**"
jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: setup workspace
        run: cp ci.package.json package.json
      - run: yarn
      - name: codegen
        run: yarn codegen
      - name: update tsconfigs for workspace
        run: .github/scripts/copy-ts-config.sh
      - name: build
        run: yarn build
